version: '3'

services:
  matterbridge:
    image: 42wim/matterbridge:latest
    container_name: matterbridge
    restart: unless-stopped
    volumes:
      - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml
    ports:
      - "9005:9005"

services:
  matterbridge:
    image: 42wim/matterbridge:latest
    volumes:
      - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml
    env_file:
      - .env
